# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=108, verbose_name='原料类别')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='cls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage.MaterialCls', verbose_name='原料类别'),
        ),
    ]
